package com.saic.prism.ws.exnomws.prismexnomws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0-SNAPSHOT-ea2e0c5846cfab98729da7c79d8dc8cf82a770c0
 * 2018-09-28T09:07:46.117-06:00
 * Generated source version: 3.3.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://PRISMExNomWS.exnomws.ws.prism.saic.com", name = "PRISMExNomWSEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface PRISMExNomWSEndPoint {

    @WebMethod
    @RequestWrapper(localName = "getExNomStatus", targetNamespace = "http://PRISMExNomWS.exnomws.ws.prism.saic.com", className = "com.saic.prism.ws.exnomws.prismexnomws.GetExNomStatus")
    @ResponseWrapper(localName = "getExNomStatusResponse", targetNamespace = "http://PRISMExNomWS.exnomws.ws.prism.saic.com", className = "com.saic.prism.ws.exnomws.prismexnomws.GetExNomStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.exnomws.prismexnomws.PrismNomStatusResponse getExNomStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.exnomws.prismexnomws.PrismDataRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "resubmitExNom", targetNamespace = "http://PRISMExNomWS.exnomws.ws.prism.saic.com", className = "com.saic.prism.ws.exnomws.prismexnomws.ResubmitExNom")
    @ResponseWrapper(localName = "resubmitExNomResponse", targetNamespace = "http://PRISMExNomWS.exnomws.ws.prism.saic.com", className = "com.saic.prism.ws.exnomws.prismexnomws.ResubmitExNomResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.exnomws.prismexnomws.PrismNomStatusResponse resubmitExNom(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.exnomws.prismexnomws.PrismExNomRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "submitExNom", targetNamespace = "http://PRISMExNomWS.exnomws.ws.prism.saic.com", className = "com.saic.prism.ws.exnomws.prismexnomws.SubmitExNom")
    @ResponseWrapper(localName = "submitExNomResponse", targetNamespace = "http://PRISMExNomWS.exnomws.ws.prism.saic.com", className = "com.saic.prism.ws.exnomws.prismexnomws.SubmitExNomResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.exnomws.prismexnomws.PrismNomStatusResponse submitExNom(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.exnomws.prismexnomws.PrismExNomRequest arg0
    );
}
