package com.saic.prism.ws.exnomws.prismexnomws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0-SNAPSHOT-ea2e0c5846cfab98729da7c79d8dc8cf82a770c0
 * 2018-09-28T09:07:46.124-06:00
 * Generated source version: 3.3.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "PRISMExNomWS",
                  wsdlLocation = "file:components/prism-client/src/main/resources/prism-wsdl/PRISMExNomWS.wsdl",
                  targetNamespace = "http://PRISMExNomWS.exnomws.ws.prism.saic.com")
public class PRISMExNomWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://PRISMExNomWS.exnomws.ws.prism.saic.com", "PRISMExNomWS");
    public final static QName PRISMExNomWSEndPointPort = new QName("http://PRISMExNomWS.exnomws.ws.prism.saic.com", "PRISMExNomWSEndPointPort");
    static {
        URL url = null;
        try {
            url = new URL("file:components/prism-client/src/main/resources/prism-wsdl/PRISMExNomWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PRISMExNomWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:components/prism-client/src/main/resources/prism-wsdl/PRISMExNomWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PRISMExNomWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PRISMExNomWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PRISMExNomWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PRISMExNomWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PRISMExNomWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PRISMExNomWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PRISMExNomWSEndPoint
     */
    @WebEndpoint(name = "PRISMExNomWSEndPointPort")
    public PRISMExNomWSEndPoint getPRISMExNomWSEndPointPort() {
        return super.getPort(PRISMExNomWSEndPointPort, PRISMExNomWSEndPoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PRISMExNomWSEndPoint
     */
    @WebEndpoint(name = "PRISMExNomWSEndPointPort")
    public PRISMExNomWSEndPoint getPRISMExNomWSEndPointPort(WebServiceFeature... features) {
        return super.getPort(PRISMExNomWSEndPointPort, PRISMExNomWSEndPoint.class, features);
    }

}
