FROM centos:7

RUN yum update -y && \
yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel && \
yum clean all

#copy files
COPY components/prism-adapter/build/libs/prism-adapter-0.0.1-SNAPSHOT.jar /tmp/
COPY scripts/services-init-prism-adapter.sh /tmp/

#run it!
RUN chmod +x /tmp/services-init-prism-adapter.sh
ENTRYPOINT "/tmp/services-init-prism-adapter.sh" && /bin/bash
EXPOSE 8082
