FROM centos:7

RUN yum update -y && \
yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel && \
yum clean all

#copy files
COPY components/api/build/libs/stargate-0.0.1-SNAPSHOT.jar /tmp/
COPY scripts/services-init-stargate-api.sh /tmp/

#run it!
RUN chmod +x /tmp/services-init-stargate-api.sh
ENTRYPOINT "/tmp/services-init-stargate-api.sh" && /bin/bash
EXPOSE 8081