package com.saic.prism.ws.coredataws.prismcoredataws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0-SNAPSHOT-ea2e0c5846cfab98729da7c79d8dc8cf82a770c0
 * 2018-09-28T09:07:45.266-06:00
 * Generated source version: 3.3.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", name = "PRISMCoreDataWSEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface PRISMCoreDataWSEndPoint {

    @WebMethod
    @RequestWrapper(localName = "getER", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetER")
    @ResponseWrapper(localName = "getERResponse", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetERResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.coredataws.prismcoredataws.PrismerResponse getER(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.coredataws.prismcoredataws.PrismMultiDataRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMission", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetMission")
    @ResponseWrapper(localName = "getMissionResponse", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetMissionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.coredataws.prismcoredataws.PrismMissionResponse getMission(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.coredataws.prismcoredataws.PrismMultiDataRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getCR", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetCR")
    @ResponseWrapper(localName = "getCRResponse", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetCRResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.coredataws.prismcoredataws.PrismcrResponse getCR(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.coredataws.prismcoredataws.PrismMultiDataRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getNOM", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetNOM")
    @ResponseWrapper(localName = "getNOMResponse", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetNOMResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.coredataws.prismcoredataws.PrismNomResponse getNOM(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.coredataws.prismcoredataws.PrismMultiDataRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTargetByID", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetTargetByID")
    @ResponseWrapper(localName = "getTargetByIDResponse", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetTargetByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.coredataws.prismcoredataws.PrismTargetResponse getTargetByID(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.coredataws.prismcoredataws.PrismMultiDataRequestId arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTarget", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetTarget")
    @ResponseWrapper(localName = "getTargetResponse", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetTargetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.coredataws.prismcoredataws.PrismTargetResponse getTarget(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.coredataws.prismcoredataws.PrismMultiDataRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getIP", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetIP")
    @ResponseWrapper(localName = "getIPResponse", targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", className = "com.saic.prism.ws.coredataws.prismcoredataws.GetIPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.coredataws.prismcoredataws.PrismipResponse getIP(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.coredataws.prismcoredataws.PrismMultiDataRequest arg0
    );
}
