package com.saic.prism.ws.coredataws.prismcoredataws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0-SNAPSHOT-ea2e0c5846cfab98729da7c79d8dc8cf82a770c0
 * 2018-09-28T09:07:45.299-06:00
 * Generated source version: 3.3.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "PRISMCoreDataWS",
                  wsdlLocation = "file:components/prism-client/src/main/resources/prism-wsdl/PRISMCoreDataWS.wsdl",
                  targetNamespace = "http://PRISMCoreDataWS.coredataws.ws.prism.saic.com")
public class PRISMCoreDataWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", "PRISMCoreDataWS");
    public final static QName PRISMCoreDataWSEndPointPort = new QName("http://PRISMCoreDataWS.coredataws.ws.prism.saic.com", "PRISMCoreDataWSEndPointPort");
    static {
        URL url = null;
        try {
            url = new URL("file:components/prism-client/src/main/resources/prism-wsdl/PRISMCoreDataWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PRISMCoreDataWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:components/prism-client/src/main/resources/prism-wsdl/PRISMCoreDataWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PRISMCoreDataWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PRISMCoreDataWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PRISMCoreDataWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PRISMCoreDataWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PRISMCoreDataWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PRISMCoreDataWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PRISMCoreDataWSEndPoint
     */
    @WebEndpoint(name = "PRISMCoreDataWSEndPointPort")
    public PRISMCoreDataWSEndPoint getPRISMCoreDataWSEndPointPort() {
        return super.getPort(PRISMCoreDataWSEndPointPort, PRISMCoreDataWSEndPoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PRISMCoreDataWSEndPoint
     */
    @WebEndpoint(name = "PRISMCoreDataWSEndPointPort")
    public PRISMCoreDataWSEndPoint getPRISMCoreDataWSEndPointPort(WebServiceFeature... features) {
        return super.getPort(PRISMCoreDataWSEndPointPort, PRISMCoreDataWSEndPoint.class, features);
    }

}
