package com.saic.prism.ws.researchws.prismresearchws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0-SNAPSHOT-ea2e0c5846cfab98729da7c79d8dc8cf82a770c0
 * 2018-09-28T09:07:45.853-06:00
 * Generated source version: 3.3.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", name = "PRISMResearchWSEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface PRISMResearchWSEndPoint {

    @WebMethod
    @RequestWrapper(localName = "getCRResearch", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetCRResearch")
    @ResponseWrapper(localName = "getCRResearchResponse", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetCRResearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.researchws.prismresearchws.PrismcrShortResponse getCRResearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.researchws.prismresearchws.PrismcrShortRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getNomResearch", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetNomResearch")
    @ResponseWrapper(localName = "getNomResearchResponse", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetNomResearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.researchws.prismresearchws.PrismNomShortResponse getNomResearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.researchws.prismresearchws.PrismNomShortRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTargetResearch", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetTargetResearch")
    @ResponseWrapper(localName = "getTargetResearchResponse", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetTargetResearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.researchws.prismresearchws.PrismTargetShortResponse getTargetResearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.researchws.prismresearchws.PrismTargetShortRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getIPResearch", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetIPResearch")
    @ResponseWrapper(localName = "getIPResearchResponse", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetIPResearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.researchws.prismresearchws.PrismipShortResponse getIPResearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.researchws.prismresearchws.PrismipShortRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getERResearch", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetERResearch")
    @ResponseWrapper(localName = "getERResearchResponse", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetERResearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.researchws.prismresearchws.PrismerShortResponse getERResearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.researchws.prismresearchws.PrismerShortRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getPIRResearch", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetPIRResearch")
    @ResponseWrapper(localName = "getPIRResearchResponse", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetPIRResearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.researchws.prismresearchws.PrismpirResponse getPIRResearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.researchws.prismresearchws.PrismpirRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMissionResearch", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetMissionResearch")
    @ResponseWrapper(localName = "getMissionResearchResponse", targetNamespace = "http://PRISMResearchWS.researchws.ws.prism.saic.com", className = "com.saic.prism.ws.researchws.prismresearchws.GetMissionResearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.saic.prism.ws.researchws.prismresearchws.PrismMissionShortResponse getMissionResearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.saic.prism.ws.researchws.prismresearchws.PrismMissionShortRequest arg0
    );
}
